### ISSUE TITLE
Can the sgx-gmp build in simulation mode？

### ISSUE THREAD

**Issue by yiyayo-wqh** [intel/sgx-gmp#1]
Hello, 

My laptop can't support Intel SGX capable hardware, and i want to use the GMP Library in enclave(via simulation mode).

My Configuration:
        Ubuntu* Linux* 16.04;
        Intel SGX SDK v2.3.1;
        No Intel SGX capable hardware;

Description:
        Firstly, I try configure the sgx-gmp trusted library, use the "--enable-sgx" arguments:
"./configure --enable-sgx --enable-static --disable-shared --enable-assembly --prefix=install_dir"
,and build it successful. But when i run the sgx-gmp-demo(The two programs, provided, demonstrate how to use the Intel SGX build of the GMP library), it shows error:
![image](https://user-images.githubusercontent.com/43172897/55681908-bcbfe000-595e-11e9-8d0d-5422bc1f0989.png)
        Then, I try configure the sgx-gmp trusted library, use the "--enable-sgx-simulation" arguments:
"./configure --enable-sgx-simulation --enable-static --disable-shared --enable-assembly --prefix=install_dir" . But it does not install "libsgx_tgmp.a", just "libgmp.a" in the library. And, when i run the sgx-gmp-demo, i shows error:
![1](https://user-images.githubusercontent.com/43172897/55682188-88e6b980-5962-11e9-8363-102598b92f5c.png)

My problem:
        1. Can I use the sgx-gmp trusted library in the simulation mode of SGX?
        2. If it is possible, how can I successfully run the demo?

Looking forward to your reply and best wishes!

Qing Hao,Wang

**Comment by jmechalas** [comment]
Yes, this should work in simulation mode. I'll take a look at this today.

**Comment by jmechalas** [comment]
You need to specify the location of the trusted gmp library when running configure. For example:

```
./configure --with-sgxsdk=/opt/intel/sgxsdk --enable-sgx-simulation --with-trusted-gmpdir=/opt/gmp/6.1.2
```

To avoid version conflicts with GMP, it's best to build both the SGX and non-SGX versions, install them to the same destination dir (e.g. /opt/gmp/6.1.2) and then use:

```
./configure --with-sgxsdk=/opt/intel/sgxsdk --enable-sgx-simulation --with-gmpdir=/opt/gmp/6.1.2
```

to set the location of both the trusted and untrusted libraries at the same time.

**Comment by yiyayo-wqh** [comment]
Thanks  @jmechalas ，
I built both the sgx-gmp and non-sgx gmp in the same destination dir: "/opt/gmp/6.1.2", and i use the file "sgx-configure" to configure the sgx-gmp, and make ,make install.
Then, i run the configure of the sgx-gmp-demo use:
"./configure --with-sgxsdk=/opt/intel/sgxsdk --enable-sgx-simulation --with-trusted-gmpdir=/opt/gmp/6.1.2", and make it.
But when i run the demo, it still shows the error :
![1](https://user-images.githubusercontent.com/43172897/56123784-c8875400-5fa7-11e9-975e-ec46f38c844c.png)
Where did I go wrong?
Kind regards you!

**Comment by jmechalas** [comment]
Make sure you pull in the latest commits on the master branch. This was one of the [fixes I made last week](https://github.com/intel/sgx-gmp-demo/commit/9533574f95b97ea08adb6724d8be797c53119dac).

**Comment by yiyayo-wqh** [comment]
Its my fault that neglect the the latest commits. Now, it works. Thanks a lot! @jmechalas
