### ISSUE TITLE
Is the sgx-gmp support c++?

### ISSUE THREAD

**Issue by zhq0918** [intel/sgx-gmp#4]
I tried the sgx-gmp,because my code is c++,when i make it,i met this problem:
/opt/gmp/6.1.2/include/sgx_tgmp.h:474:12: error: ‘std::FILE’ has not been declared
 using std::FILE;
            ^
/opt/gmp/6.1.2/include/sgx_tgmp.h:2283:24: error: ‘ostream’ in namespace ‘std’ does not name a type
 __GMP_DECLSPEC_XX std::ostream& operator<< (std::ostream &, mpz_srcptr);
                        ^
/opt/gmp/6.1.2/include/sgx_tgmp.h:2284:24: error: ‘ostream’ in namespace ‘std’ does not name a type
 __GMP_DECLSPEC_XX std::ostream& operator<< (std::ostream &, mpq_srcptr);
                        ^
/opt/gmp/6.1.2/include/sgx_tgmp.h:2285:24: error: ‘ostream’ in namespace ‘std’ does not name a type
 __GMP_DECLSPEC_XX std::ostream& operator<< (std::ostream &, mpf_srcptr);
                        ^
/opt/gmp/6.1.2/include/sgx_tgmp.h:2286:24: error: ‘istream’ in namespace ‘std’ does not name a type
 __GMP_DECLSPEC_XX std::istream& operator>> (std::istream &, mpz_ptr);
                        ^
/opt/gmp/6.1.2/include/sgx_tgmp.h:2287:24: error: ‘istream’ in namespace ‘std’ does not name a type
 __GMP_DECLSPEC_XX std::istream& operator>> (std::istream &, mpq_ptr);
                        ^
/opt/gmp/6.1.2/include/sgx_tgmp.h:2288:24: error: ‘istream’ in namespace ‘std’ does not name a type
 __GMP_DECLSPEC_XX std::istream& operator>> (std::istream &, mpf_ptr);

The sgx-gmp can't support c++ ?

**Comment by jmechalas** [comment]
It's actually on my to-do list, but it's not been done yet (I took an early pass at it but never completed it).

If you want to do the port and send a pull request though I'd be pretty thrilled! :)

**Comment by zhq0918** [comment]
hi，@jmechalas,  One of our projects needs mpir, and we need to operate mpz_class and other related classes such as "std::ostream(which in sgx_tgmp.h line 2283)"  in Enclave. I think mpir and GMP have similar functions. Now, I'm studying gmp.
